name: Twilio Continuous Deployment

on:
  push:
    branches:
      - main
      - dev1
      - dev2
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies for the twilio function
        run: npm install
      - name: twilio-cli
        run: npm install -g twilio-cli
      - name: twilio serverless
        run: twilio plugins:install @twilio-labs/plugin-serverless@v3
      - name: Transpile with Babel ESM syntax to CJS
        run: npm run transpile
      - name: twilio serverless:deploy
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: twilio serverless:deploy --environment ${{ github.ref_name	}} > deployment_output.txt
      - name: Update phone number url
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
        run: |
          URL=$(grep -o 'https://[a-zA-Z0-9.-]*\.twil\.io/transcribe' deployment_output.txt)
          if [[ ${{ github.ref_name }} == "main"  ]]; then
            phone_number="+447862132308"
          elif [[ ${{ github.ref_name }} == "dev1"  ]]; then
            phone_number="+447488890677"
          else
            phone_number="+447488898879"
          fi
          twilio phone-numbers update $phone_number --voice-url=$URL --voice-method=POST
